In [2]:
import pandas as pd
import numpy as np
card = pd.read_csv("Downloads/CardKrueger.csv")
card.head()

,sheet,chain,co_owned,state,southj,centralj,northj,pa1,pa2,shore,...,firstin2,special2,meals2,open2r,hrsopen2,psoda2,pfry2,pentree2,nregs2,nregs112
0,1,1,0,1,0,1,0,0,0,0,...,NaN,0.0,reduced,7.0,16.0,1.05,0.79,0.90,4.0,3.0
1,2,1,0,1,0,1,0,0,0,0,...,0.38,1.0,free,7.0,15.0,1.05,1.01,0.94,2.0,2.0
2,3,2,0,1,0,1,0,0,0,0,...,0.25,0.0,free,11.0,11.0,1.05,0.94,2.75,5.0,3.0
3,4,3,0,1,0,1,0,0,0,0,...,0.28,0.0,reduced,8.0,13.5,1.22,1.37,0.89,6.0,4.0
4,5,3,0,1,0,1,0,0,0,0,...,0.18,0.0,reduced,6.0,17.0,1.05,0.94,0.94,5.0,5.0

In [11]:
#Question 1

card['empfte'] = card['empft']+0.5*card['emppt']+card['nmgrs']
card['empfte2'] = card['empft2']+0.5*card['emppt2']+card['nmgrs2']
card

,sheet,chain,co_owned,state,southj,centralj,northj,pa1,pa2,shore,...,open2r,hrsopen2,psoda2,pfry2,pentree2,nregs2,nregs112,empfte,empfte2,change
0,1,1,0,1,0,1,0,0,0,0,...,7.0,16.0,1.05,0.79,0.90,4.0,3.0,35.00,44.0,9.00
1,2,1,0,1,0,1,0,0,0,0,...,7.0,15.0,1.05,1.01,0.94,2.0,2.0,16.00,15.5,-0.50
2,3,2,0,1,0,1,0,0,0,0,...,11.0,11.0,1.05,0.94,2.75,5.0,3.0,15.50,10.5,-5.00
3,4,3,0,1,0,1,0,0,0,0,...,8.0,13.5,1.22,1.37,0.89,6.0,4.0,19.00,24.0,5.00
4,5,3,0,1,0,1,0,0,0,0,...,6.0,17.0,1.05,0.94,0.94,5.0,5.0,24.00,29.0,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,514,3,0,2,0,0,0,0,1,0,...,6.0,16.0,0.95,0.95,1.05,6.0,4.0,18.00,34.0,16.00
406,515,3,1,2,0,0,0,0,1,0,...,6.0,16.0,1.01,1.01,0.94,5.0,4.0,19.00,17.5,-1.50
407,516,3,1,2,0,0,0,0,1,0,...,8.0,14.0,1.01,0.95,0.89,5.0,3.0,20.25,10.0,-10.25
408,521,1,0,2,0,0,0,1,0,0,...,7.0,16.0,0.41,0.84,0.89,4.0,2.0,15.50,14.0,-1.50
409,522,1,0,2,0,0,0,1,0,0,...,7.0,16.0,1.00,0.74,0.95,3.0,3.0,21.00,17.5,-3.50

In [4]:
#Question 2

grouped = card.groupby('state')

# Applying a function to each group, for example, calculating the mean
mean_employ_before = grouped['empfte'].mean()
mean_employ_before
mean_employ_after = grouped['empfte2'].mean()
mean_employ_after
merged_df = pd.merge(mean_employ_before, mean_employ_after, on='state', how='left')
merged_df
mean_employ_after-mean_employ_before

#We found employment increased by 0.588021 in New Jersey and decreased by -2.165584 in Pennsylvania. 
#These measures don't control for time variant factors such as inflation that might confound the estimate so are flawed estimates.

state
1    0.588021
2   -2.165584
dtype: float64

In [5]:
#Question 3

(mean_employ_after[1]-mean_employ_before[1])-(mean_employ_after[2]-mean_employ_before[2])

2.753605782980582

In [12]:
#Question 4
card['change'] = card['empfte2']-card['empfte']

nj = card[card['state'] == 1]
penn = card[card['state'] == 2]

from scipy import stats

# Perform independent t-test
t_statistic, p_value = stats.ttest_ind(nj['change'], penn['change'], nan_policy='omit')

# Print the results
print("T-statistic:", t_statistic)
print("P-value:", p_value)

#It is statistically significant at a threshold of p < 0.05. 

card

T-statistic: 2.3822819671780957
P-value: 0.01769432588830923

,sheet,chain,co_owned,state,southj,centralj,northj,pa1,pa2,shore,...,open2r,hrsopen2,psoda2,pfry2,pentree2,nregs2,nregs112,empfte,empfte2,change
0,1,1,0,1,0,1,0,0,0,0,...,7.0,16.0,1.05,0.79,0.90,4.0,3.0,35.00,44.0,9.00
1,2,1,0,1,0,1,0,0,0,0,...,7.0,15.0,1.05,1.01,0.94,2.0,2.0,16.00,15.5,-0.50
2,3,2,0,1,0,1,0,0,0,0,...,11.0,11.0,1.05,0.94,2.75,5.0,3.0,15.50,10.5,-5.00
3,4,3,0,1,0,1,0,0,0,0,...,8.0,13.5,1.22,1.37,0.89,6.0,4.0,19.00,24.0,5.00
4,5,3,0,1,0,1,0,0,0,0,...,6.0,17.0,1.05,0.94,0.94,5.0,5.0,24.00,29.0,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,514,3,0,2,0,0,0,0,1,0,...,6.0,16.0,0.95,0.95,1.05,6.0,4.0,18.00,34.0,16.00
406,515,3,1,2,0,0,0,0,1,0,...,6.0,16.0,1.01,1.01,0.94,5.0,4.0,19.00,17.5,-1.50
407,516,3,1,2,0,0,0,0,1,0,...,8.0,14.0,1.01,0.95,0.89,5.0,3.0,20.25,10.0,-10.25
408,521,1,0,2,0,0,0,1,0,0,...,7.0,16.0,0.41,0.84,0.89,4.0,2.0,15.50,14.0,-1.50
409,522,1,0,2,0,0,0,1,0,0,...,7.0,16.0,1.00,0.74,0.95,3.0,3.0,21.00,17.5,-3.50

In [10]:
#Question 5

card.head()

reshaped = card[['empfte', 'empfte2']]
reshaped

     empfte  empfte2
0     35.00     44.0
1     16.00     15.5
2     15.50     10.5
3     19.00     24.0
4     24.00     29.0
..      ...      ...
405   18.00     34.0
406   19.00     17.5
407   20.25     10.0
408   15.50     14.0
409   21.00     17.5

[410 rows x 2 columns]

In [41]:
#Question 6 

card['i'] = card.index
reshaped = card[['i','empfte', 'empfte2', 'state']]
reshaped.loc[:, 'nj'] = np.where(reshaped['state'] == 1, 1, 0)

reshaped = reshaped.drop('state', axis=1)

reshaped

# Pivot longer using melt()
reshaped_2 = pd.melt(reshaped, id_vars=['i','nj'], var_name='Post', value_name='Y')

reshaped_2['Post'] = np.where(reshaped_2['Post'] == "empfte", 0, 1)

print(reshaped_2)

       i  nj  Post     Y
0      0   1     0  35.0
1      1   1     0  16.0
2      2   1     0  15.5
3      3   1     0  19.0
4      4   1     0  24.0
..   ...  ..   ...   ...
815  405   0     1  34.0
816  406   0     1  17.5
817  407   0     1  10.0
818  408   0     1  14.0
819  409   0     1  17.5

[820 rows x 4 columns]

/var/folders/sb/wkgkxhms7671rqjklclt6qlh0000gn/T/ipykernel_47173/1292937662.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reshaped.loc[:, 'nj'] = np.where(reshaped['state'] == 1, 1, 0)

In [37]:
#Question 7

import statsmodels.api as sm

model = sm.formula.ols(formula='Y ~ nj + Post + nj:Post', data=reshaped_2).fit()

print(model.summary())

#The DD estimate is 2.7536. Yes, the regression coefficient of our interaction term is the 
#same as our result from Question 3. The standard error is 1.688 for the interaction term.

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.964
Date:                Thu, 18 Apr 2024   Prob (F-statistic):              0.118
Time:                        16:44:00   Log-Likelihood:                -2904.2
No. Observations:                 794   AIC:                             5816.
Df Residuals:                     790   BIC:                             5835.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     23.3312      1.072     21.767      0.000      21.227      25.435
nj            -2.8918      1.194     -2.423      0.016      -5.235      -0.549
Post          -2.1656      1.516     -1.429      0.154      -5.141       0.810
nj:Post        2.7536      1.688      1.631      0.103      -0.561       6.068
==============================================================================
Omnibus:                      218.742   Durbin-Watson:                   1.776
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              804.488
Skew:                           1.268   Prob(JB):                    2.03e-175
Kurtosis:                       7.229   Cond. No.                         11.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
#Question 8

#The P Value of the interaction term is 0.103 which is greater than the typical P Value of 
#0.05, so it is not significant. 
#The P Value in Question 4 is likely less accurate because it doesn't control for 
#confounders, unlike this regression which has an interaction term.

In [42]:
#Question 9

card['i'] = card.index
reshaped_ft = card[['i','empft', 'empft2', 'state']]
reshaped_ft.loc[:, 'nj'] = np.where(reshaped_ft['state'] == 1, 1, 0)

reshaped_ft = reshaped_ft.drop('state', axis=1)

reshaped_ft

# Pivot longer using melt()
full = pd.melt(reshaped_ft, id_vars=['i','nj'], var_name='Post', value_name='Y')

full['Post'] = np.where(full['Post'] == "empft", 0, 1)

model_full = sm.formula.ols(formula='Y ~ nj + Post + nj:Post', data=full).fit()

print(model_full.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.008
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     2.122
Date:                Thu, 18 Apr 2024   Prob (F-statistic):             0.0959
Time:                        16:59:05   Log-Likelihood:                -2831.4
No. Observations:                 802   AIC:                             5671.
Df Residuals:                     798   BIC:                             5690.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.2051      0.938     10.883      0.000       8.365      12.046
nj            -2.4812      1.044     -2.377      0.018      -4.530      -0.432
Post          -2.6402      1.330     -1.985      0.048      -5.252      -0.029
nj:Post        3.3617      1.481      2.270      0.023       0.454       6.269
==============================================================================
Omnibus:                      242.796   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              677.203
Skew:                           1.524   Prob(JB):                    8.86e-148
Kurtosis:                       6.313   Cond. No.                         11.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/var/folders/sb/wkgkxhms7671rqjklclt6qlh0000gn/T/ipykernel_47173/383638749.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reshaped_ft.loc[:, 'nj'] = np.where(reshaped_ft['state'] == 1, 1, 0)

In [43]:
card['i'] = card.index
reshaped_pt = card[['i','emppt', 'emppt2', 'state']]
reshaped_pt.loc[:, 'nj'] = np.where(reshaped_pt['state'] == 1, 1, 0)

reshaped_pt = reshaped_pt.drop('state', axis=1)

reshaped_pt

# Pivot longer using melt()
part = pd.melt(reshaped_pt, id_vars=['i','nj'], var_name='Post', value_name='Y')

part['Post'] = np.where(part['Post'] == "emppt", 0, 1)

model_part = sm.formula.ols(formula='Y ~ nj + Post + nj:Post', data=part).fit()

print(model_part.summary())

#Based off of these regressions, the number of full time employees increased and the number 
#of part time employees decreased (although for part time the p value was very high). This 
#suggestions their hypothesis is wrong.

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.001
Method:                 Least Squares   F-statistic:                    0.6227
Date:                Thu, 18 Apr 2024   Prob (F-statistic):              0.600
Time:                        17:01:26   Log-Likelihood:                -3028.7
No. Observations:                 806   AIC:                             6065.
Df Residuals:                     802   BIC:                             6084.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     19.4872      1.177     16.558      0.000      17.177      21.797
nj            -0.8119      1.309     -0.620      0.535      -3.382       1.758
Post           0.4674      1.670      0.280      0.780      -2.810       3.745
nj:Post       -0.7696      1.858     -0.414      0.679      -4.417       2.877
==============================================================================
Omnibus:                       74.882   Durbin-Watson:                   1.763
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               94.520
Skew:                           0.783   Prob(JB):                     2.99e-21
Kurtosis:                       3.599   Cond. No.                         11.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/var/folders/sb/wkgkxhms7671rqjklclt6qlh0000gn/T/ipykernel_47173/1478909159.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reshaped_pt.loc[:, 'nj'] = np.where(reshaped_pt['state'] == 1, 1, 0)